---
- name: Install curl
  apt: name=curl state=present

- command: node --version | sed -e 's/^v10.*$/10/'
  register: node_version
  ignore_errors: True

- name: Adding source for node 10
  command:  bash -c "curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -" 
  when: node_version != "10"
    
- name: Install node
  apt: name=nodejs state=present

- name: Install grunt cli
  npm: 
    name: grunt-cli
    global: yes
